FROM node:22

# ตั้ง working directory
WORKDIR /app

# คัดลอกไฟล์ package.json และ package-lock.json (หรือตัวอย่างอื่นๆ ที่เกี่ยวข้อง)
COPY package*.json ./

# ติดตั้ง dependencies
RUN npm install

# คัดลอกไฟล์ทั้งหมดในโปรเจคไปที่ container
# COPY . .

# สร้างโปรเจค (ถ้าจำเป็น)
# RUN npm run build
# RUN npm run dev

CMD ["npm", "run", "dev"]