services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - react
      - nestjs

  react:
    # image: node:22
    container_name: react
    build: ./upload-web
    # working_dir: /app
    # command: sh -c "npm install && npm run dev"
    ports:
      - "3001:3003"
    volumes:
      - ./upload-web:/app
      - /app/node_modules
    stdin_open: true

  nestjs:
    image: node:22
    container_name: nestjs
    working_dir: /app
    command: sh -c "npm install && npm run start:dev"
    ports:
      - "5001:5001"
    volumes:
      - ./upload-api:/app
      - /app/node_modules
      - uploadfile:/app/upload
    environment:
      - PORT=5001
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    networks:
      - network-upload

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    networks:
      - network-upload

  db:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network-upload

volumes:
  uploadfile:
  minio_data:
  postgres_data:

networks:
  network-upload:
