services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8080:3090"
      - "8090:5090"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - react
      - nestjs
    networks:
      - network_upload

  react:
    # image: node:22
    container_name: react
    build: ./upload-web
    ports:
      - "3000:3002"
    volumes:
      - ./upload-web:/app
      # - /app/node_modules
      - react_module:/app/node_modules
    environment:
      - HOST=react
      - PORT=3002
    stdin_open: true
    networks:
      - network_upload

  nestjs:
    image: node:22
    container_name: nestjs
    working_dir: /app
    command: sh -c "npm install && npm run start:dev"
    ports:
      - "5000:5000"
    volumes:
      - ./upload-api:/app
      - nestjs_module:/app/node_modules
    environment:
      - PORT=5000
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
      - db
    networks:
      - network_upload

  minio:
    image: minio/minio
    container_name: minio
    working_dir: /app
    ports:
      - "9000:9000" # API Port
      - "9090:9090" # Console Port
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    volumes:
      - ./minio_data:/app
    command: server /app --console-address ":9090"
    networks:
      - network_upload

  db:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - network_upload
    
  # pgadmin4:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin4-2
  #   # working_dir: /app
  #   ports: 
  #     - "5050:80"
  #   # volumns:
  #   #   - ./pgadmin4:/app
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=user@domain.com
  #     - PGADMIN_DEFAULT_PASSWORD=SuperSecret
  #   networks:
  #     - network_upload

volumes:
  nestjs_module:
  react_module:
  minio_data:
#   postgres_data:

networks:
  network_upload:
